- name: Ensure directory {{ lookup('env','HOME') }}/.config/systemd/user exists
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.config/systemd/user"
    state: directory
    mode: '0755'
    recurse: yes

- name: Copy user services and timers {{ task_identifier }}
  ansible.builtin.template:
    src: "templates/systemd/ {{ systemd_service.name }}"
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{systemd_service.name}}"
  loop: "{{ host.systemd }}"
  loop_control:
    loop_var: systemd_service

- name: Enable and start user systemd services {{ task_identifier }}
  ansible.builtin.systemd:
    name: "{{ systemd_service.name }}"
    state: "{{ systemd_service.state }}"
    enabled: "{{ systemd_service.enabled }}"
    scope: user
  loop: "{{ host.systemd }}"
  loop_control:
    loop_var: systemd_service
