- name: Manage overlay packages {{ task_identifier }}
  tags: [rpm-ostree]
  community.general.rpm_ostree_pkg:
    name: "{{ rpm_ostree_pkg.name }}"
    state: "{{ rpm_ostree_pkg.state }}"
  loop: "{{ host.layered_packages }}"
  loop_control:
    loop_var: rpm_ostree_pkg
    label: {'name': '{{ rpm_ostree_pkg.name }}', 'state': '{{ rpm_ostree_pkg.state }}'}
  register: rpm_ostree_pkg_install
