remotes:
  - name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system

  - name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    method: system

flatpaks:
  - name: org.gimp.GIMP
    state: present
    method: system
    remote: flathub-beta
    cmds: [gimp]

  - name: io.neovim.nvim
    state: present
    method: system
    remote: flathub
    cmds: [vi, vim, nvim]
    overrides:
      - { name: "--filesystem=/tmp", scope: user }
      - { name: "--env=TERM=xterm-256color", scope: user }

  - name: com.github.tchx84.Flatseal
    state: present
    method: system
    remote: flathub

  - name: org.kde.neochat
    state: present
    method: system
    remote: flathub
