- name: kinoite-test
  tasks: 
    - playbooks/host/tasks_host_default.yaml
    - playbooks/host/tasks_host_rpm_ostree.yaml
    - playbooks/host/tasks_host_systemd.yaml

  layered_packages:
    - { name: exa, state: present }
    - { name: bat, state: present }
    - { name: fish, state: present }
